// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRN231_FinalProject_API.Models;

#nullable disable

namespace PRN231_FinalProject_API.Migrations
{
    [DbContext(typeof(PRN221_ProjectContext))]
    partial class PRN221_ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PRN231_FinalProject_API.Models.AutomatedTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("TransactionId")
                        .HasName("PK__Automate__55433A4B8458CB5B");

                    b.HasIndex("UserId");

                    b.ToTable("AutomatedTransactions");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Budget", b =>
                {
                    b.Property<int?>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BudgetID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("BudgetId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Month")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalBudget")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CurrencyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrencyId"), 1L, 1);

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.DebtsLoan", b =>
                {
                    b.Property<int>("DebtLoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DebtLoanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DebtLoanId"), 1L, 1);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("DebtLoanId")
                        .HasName("PK__DebtsLoa__27937CA54E86BB1A");

                    b.HasIndex("UserId");

                    b.ToTable("DebtsLoans");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.ExchangeRate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RateID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateId"), 1L, 1);

                    b.Property<int?>("FromCurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("FromCurrencyID");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(15,6)");

                    b.Property<int?>("ToCurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("ToCurrencyID");

                    b.HasKey("RateId")
                        .HasName("PK__Exchange__58A7CCBC6C54BE80");

                    b.HasIndex("FromCurrencyId");

                    b.HasIndex("ToCurrencyId");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExpenseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"), 1L, 1);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ExpenseId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.FinancialProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ProductId")
                        .HasName("PK__Financia__B40CC6EDAB05DAE6");

                    b.ToTable("FinancialProducts");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IncomeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomeId"), 1L, 1);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IncomeDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("IncomeId");

                    b.HasIndex("UserId");

                    b.ToTable("Income", (string)null);
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Investment", b =>
                {
                    b.Property<int>("InvestmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InvestmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestmentId"), 1L, 1);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InvestmentDate")
                        .HasColumnType("date");

                    b.Property<string>("InvestmentType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("InvestmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.PaymentReminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReminderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReminderId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReminderId")
                        .HasName("PK__PaymentR__01A830A73A80C0F7");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentReminders");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.ProductComparison", b =>
                {
                    b.Property<int>("ComparisonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComparisonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComparisonId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ComparisonId")
                        .HasName("PK__ProductC__6E1F99B76F7081E8");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductComparisons");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Security", b =>
                {
                    b.Property<int>("SecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecurityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecurityId"), 1L, 1);

                    b.Property<string>("EncryptionKey")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("SecurityId");

                    b.HasIndex("UserId");

                    b.ToTable("Security", (string)null);
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.TransactionLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"), 1L, 1);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogId")
                        .HasName("PK__Transact__5E5499A8A90EAF76");

                    b.HasIndex("UserId");

                    b.ToTable("TransactionLogs");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .HasColumnType("money");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.AutomatedTransaction", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.User", "User")
                        .WithMany("AutomatedTransactions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Automated__UserI__4F7CD00D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Budget", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Budgets__UserID__5070F446");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.DebtsLoan", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.User", "User")
                        .WithMany("DebtsLoans")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__DebtsLoan__UserI__5165187F");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.ExchangeRate", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.Currency", "FromCurrency")
                        .WithMany("ExchangeRateFromCurrencies")
                        .HasForeignKey("FromCurrencyId")
                        .HasConstraintName("FK__ExchangeR__FromC__52593CB8");

                    b.HasOne("PRN231_FinalProject_API.Models.Currency", "ToCurrency")
                        .WithMany("ExchangeRateToCurrencies")
                        .HasForeignKey("ToCurrencyId")
                        .HasConstraintName("FK__ExchangeR__ToCur__534D60F1");

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Expense", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Expenses__UserID__5441852A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Income", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.User", "User")
                        .WithMany("Incomes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Income__UserID__5535A963");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Investment", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.User", "User")
                        .WithMany("Investments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Investmen__UserI__5629CD9C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.PaymentReminder", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.User", "User")
                        .WithMany("PaymentReminders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__PaymentRe__UserI__571DF1D5");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.ProductComparison", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.FinancialProduct", "Product")
                        .WithMany("ProductComparisons")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__ProductCo__Produ__5812160E");

                    b.HasOne("PRN231_FinalProject_API.Models.User", "User")
                        .WithMany("ProductComparisons")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ProductCo__UserI__59063A47");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Security", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.User", "User")
                        .WithMany("Securities")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Security__UserID__59FA5E80");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.TransactionLog", b =>
                {
                    b.HasOne("PRN231_FinalProject_API.Models.User", "User")
                        .WithMany("TransactionLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Transacti__UserI__5AEE82B9");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.Currency", b =>
                {
                    b.Navigation("ExchangeRateFromCurrencies");

                    b.Navigation("ExchangeRateToCurrencies");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.FinancialProduct", b =>
                {
                    b.Navigation("ProductComparisons");
                });

            modelBuilder.Entity("PRN231_FinalProject_API.Models.User", b =>
                {
                    b.Navigation("AutomatedTransactions");

                    b.Navigation("Budgets");

                    b.Navigation("DebtsLoans");

                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("Investments");

                    b.Navigation("PaymentReminders");

                    b.Navigation("ProductComparisons");

                    b.Navigation("Securities");

                    b.Navigation("TransactionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
